# List of all the worlds which MobManager is active in
# MobManager will not have any effect on worlds not listed here
EnabledWorlds:
- world
- world_nether
- world_the_end

# MobTypes:
#    Monsters:       Blaze, Creeper, Enderman, Giant,
#                    Silverfish, Skeleton, Spider, CaveSpider,
#                    Witch, Wither, Zombie, PigZombie, Ghast,
#                    Slime, MagmaCube
#
#    Animals:        Chicken, Cow, MushroomCow, Ocelot,
#                    Pig, Sheep, Wolf, IronGolem, Snowman
#
#    Water_Animals:  Squid
#
#    Ambient:         Bat
#
#    Villager:        Villager

# Mob limits for each world for each type of mob
WorldMaximum:
  world:
    Monsters: 512
    Animals: 320
    Water_Animals: 128
    Ambient: 64
    Villager: 64
  world_nether:
    Monsters: 512
    Animals: 64
    Water_Animals: 0
    Ambient: 64
    Villager: 0
  world_the_end:
    Monsters: 256
    Animals: 0
    Water_Animals: 0
    Ambient: 64
    Villager: 0


# Limits to the number of mobs dynamically calculated
#    by the number of loaded chunks in the world
#
# Calculated with the below formula
# maxMobs = ( Number of active chunks * Config Value ) / 256
ChunkCalculatedMaximum:
  world:
    Monsters: 16
    Animals: 8
    Water_Animals: 2
    Ambient: 4
    Villager: 5
  world_nether:
    Monsters: 16
    Animals: 2
    Water_Animals: 0
    Ambient: 0
    Villager: 0
  world_the_end:
    Monsters: 16
    Animals: 0
    Water_Animals: 0
    Ambient: 0
    Villager: 0

# Stops animals from breeding if there are
#   too many animals in the chunk
BreedingMaximumsPerChunk:
  world: 20
  world_nether: 10
  world_the_end: 0

# The distance (in chunks) to scan for
#   nearby players when a mob spawns
SpawnChunkDistance: 6

# How many extra layers below normal will be checked
#   for players when a flying mob attempts to spawn
#
# This allows a higher chance for flying mobs to spawn
FlyingMobAditionalLayerDepth: 2

# How often (In ticks, 20 ticks = 1 second) the mobs
#    in a world is allowed to be recounted
#
# MobManager can only keep track of mob deaths, not mob despawns
# The lower this number the less often monsters will go above the
#   current maximum mob values
# NOTE: Mobs can be spawned over their limits by other plugins, 
#		spawn eggs as they are not prevented
#       (Perhaps an option to do so in a later version of MobManager?)
#
# NOTE: MobManager also can't count mobs which are removed
#       by other plugins (Depending on how its done)
#       So decreasing this count will also decrease the time it
#       takes for mobs to respawn
TicksPerRecount: 40

# Layers to use
# Each layer stores the players within them
# Layers at the same heights are checked around mob spawns
# The mob spawn is only allowed if one of the layers
#   checked contains a player
#
# Layers should overlap to give an even distribution of mobs
Layers:
- '0:16'
- '8:24'
- '16:32'
- '24:40'
- '32:48'
- '40:56'
- '48:64'
- '56:72'
- '64:80'
- '72:88'
- '80:96'
- '88:104'
- '96:112'
- '104:120'
- '112:128'
- '120:136'
- '128:144'
- '136:152'
- '144:160'
- '152:168'
- '160:176'
- '168:184'
- '176:192'
- '184:200'
- '192:208'
- '200:216'
- '208:224'
- '216:232'
- '224:240'
- '232:248'
- '240:256'
