main: com.forgenz.mobmanager.P
name: MobManager
version: 0.1
authors: [Michael McKnight(ShadowDog007)]
description: MobManager made for ForgeNZ to give the illusion of having more mobs while having less

# Perms coming soonish
# permissions:


# Commands coming soonish
# commands: