main: com.forgenz.mobmanager.P
name: MobManager
version: 2.5
website: http://dev.bukkit.org/server-mods/mobmanager/
author: Michael McKnight (ShadowDog007)
description: MobManager made for ForgeNZ to give the illusion of having more mobs while having less

# Soft-Depends a few multi-world plugins so the the worlds are deffinately around when MobManager needs them
softdepend: [EpicMobsRecoded,  Multiverse-Core, My Worlds, MultiWorld]

permissions:
  mobmanager.admin:
    description: Gives access to all admin commands
    default: op
    children:
      mobmanager.butcher: true
      mobmanager.count: true
      mobmanager.reload: true
      mobmanager.spawn: true
      mobmanager.pspawn: true
      mobmanager.abilitysetlist: true
      mobmanager.mobtypes: true
      mobmanager.debug: true
      mobmanager.version: true
    
  mobmanager.butcher:
    description: Gives access to the /mm butcher command
  mobmanager.count:
    description: Gives access to the /mm count command
  mobmanager.reload:
    description: Gives access to the /mm reload command
  mobmanager.spawn:
    description: Gives access to the /mm spawn command
  mobmanager.pspawn:
    description: Gives access to the /mm pspawn command
  mobmanager.abilitysetlist:
    description: Gives access to the /mm abilitysets command
  mobmanager.mobtypes:
    description: Gives access to the /mm mobtypes command
  mobmanager.version:
    description: Gives access to the /mm version command
  mobmanager.debug:
    description: Gives access to the /mm debug command

commands:
  mm:
    aliases: [mobmanager]
    description: 'MobManager command'
    permission:
    permission-message: '[MobManager] You do not have permissions to access this command'