# List of all the worlds which MobManager is active in
EnabledWorlds:
- world
- world_nether
- world_the_end

# Mob limits for each world for each type of mob
WorldMaximum:
  world:
    Monsters: 512
    Animals: 320
    Squid: 128
  world_nether:
    Monsters: 512
    Animals: 64
    Squid: 0
  world_the_end:
    Monsters: 256
    Animals: 0
    Squid: 0


# Limits to the number of mobs dynamically calculated by the number of loaded chunks in the world
# Calculated with the below formula
# maxMobs = ( Number of active chunks * Config Value ) / 256
ChunkCalculatedMaximum:
  world:
    Monsters: 6
    Animals: 4
    Squid: 1
  world_nether:
    Monsters: 8
    Animals: 2
    Squid: 0
  world_the_end:
    Monsters: 10
    Animals: 0
    Squid: 0

# Stops animals from breeding if there are too many animals in the chunk
BreedingMaximumsPerChunk:
  world: 20
  world_nether: 10
  world_the_end: 0

# The distance (in chunks) to scan for nearby players
SpawnChunkDistance: 6

# Each layer
Layers:
- '0:16'
- '8:24'
- '16:32'
- '24:40'
- '32:48'
- '40:56'
- '48:64'
- '56:72'
- '64:80'
- '72:88'
- '80:96'
- '88:104'
- '96:112'
- '104:120'
- '112:128'
- '120:136'
- '128:144'
- '136:152'
- '144:160'
- '152:168'
- '160:176'
- '168:184'
- '176:192'
- '184:200'
- '192:208'
- '200:216'
- '208:224'
- '216:232'
- '224:240'
- '232:248'
- '240:256'
