main: com.forgenz.mobmanager.P
name: MobManager
version: 1.6
authors: [Michael McKnight (ShadowDog007)]
description: MobManager made for ForgeNZ to give the illusion of having more mobs while having less

permissions:
  mobmanager.admin:
    description: Gives access to all admin commands
    default: op

commands:
  mm:
    description: 'MobManager command'
    permission: mobmanager.admin
    permission-message: '[MobManager] You do not have permissions to access this command'